// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/tags": {
    params: {};
  };
  "/api/tags/search": {
    params: {};
  };
  "/api/tags/:tagId": {
    params: {
      "tagId": string;
    };
  };
  "/journey": {
    params: {};
  };
  "/journey/:id": {
    params: {
      "id": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/admin/journeys": {
    params: {};
  };
  "/admin/:journeyId": {
    params: {
      "journeyId": string;
    };
  };
  "/admin/:journeyId/altitude-info": {
    params: {
      "journeyId": string;
    };
  };
  "/admin/:journeyId/altitude-info/:altitudeInfoId": {
    params: {
      "journeyId": string;
      "altitudeInfoId": string;
    };
  };
  "/admin/:journeyId/epics": {
    params: {
      "journeyId": string;
    };
  };
  "/admin/:journeyId/epics/:epicId": {
    params: {
      "journeyId": string;
      "epicId": string;
    };
  };
  "/admin/:journeyId/stories": {
    params: {
      "journeyId": string;
    };
  };
  "/admin/:journeyId/stories/:storyId": {
    params: {
      "journeyId": string;
      "storyId": string;
    };
  };
  "/admin/:journeyId/tags": {
    params: {
      "journeyId": string;
    };
  };
  "/documentation": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/tags" | "/api/tags/search" | "/api/tags/:tagId" | "/journey" | "/journey/:id" | "/admin" | "/admin/journeys" | "/admin/:journeyId" | "/admin/:journeyId/altitude-info" | "/admin/:journeyId/altitude-info/:altitudeInfoId" | "/admin/:journeyId/epics" | "/admin/:journeyId/epics/:epicId" | "/admin/:journeyId/stories" | "/admin/:journeyId/stories/:storyId" | "/admin/:journeyId/tags" | "/documentation";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/api.tags.ts": {
    id: "routes/api.tags";
    page: "/api/tags";
  };
  "routes/api.tags.search.ts": {
    id: "routes/api.tags.search";
    page: "/api/tags/search";
  };
  "routes/api.tags.$tagId.ts": {
    id: "routes/api.tags.$tagId";
    page: "/api/tags/:tagId";
  };
  "routes/journey.tsx": {
    id: "routes/journey";
    page: "/journey" | "/journey/:id";
  };
  "routes/journey._index.tsx": {
    id: "routes/journey._index";
    page: "/journey";
  };
  "routes/journey.$id.tsx": {
    id: "routes/journey.$id";
    page: "/journey/:id";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/journeys" | "/admin/:journeyId" | "/admin/:journeyId/altitude-info" | "/admin/:journeyId/altitude-info/:altitudeInfoId" | "/admin/:journeyId/epics" | "/admin/:journeyId/epics/:epicId" | "/admin/:journeyId/stories" | "/admin/:journeyId/stories/:storyId" | "/admin/:journeyId/tags";
  };
  "routes/admin._index.tsx": {
    id: "routes/admin._index";
    page: "/admin";
  };
  "routes/admin.journeys.tsx": {
    id: "routes/admin.journeys";
    page: "/admin/journeys";
  };
  "routes/admin.$journeyId.tsx": {
    id: "routes/admin.$journeyId";
    page: "/admin/:journeyId" | "/admin/:journeyId/altitude-info" | "/admin/:journeyId/altitude-info/:altitudeInfoId" | "/admin/:journeyId/epics" | "/admin/:journeyId/epics/:epicId" | "/admin/:journeyId/stories" | "/admin/:journeyId/stories/:storyId" | "/admin/:journeyId/tags";
  };
  "routes/admin.$journeyId._index.tsx": {
    id: "routes/admin.$journeyId._index";
    page: "/admin/:journeyId";
  };
  "routes/admin.altitude-info.tsx": {
    id: "routes/admin.altitude-info";
    page: "/admin/:journeyId/altitude-info";
  };
  "routes/admin.$journeyId.altitude-info.$altitudeInfoId.tsx": {
    id: "routes/admin.$journeyId.altitude-info.$altitudeInfoId";
    page: "/admin/:journeyId/altitude-info/:altitudeInfoId";
  };
  "routes/admin.epics.tsx": {
    id: "routes/admin.epics";
    page: "/admin/:journeyId/epics";
  };
  "routes/admin.$journeyId.epics.$epicId.tsx": {
    id: "routes/admin.$journeyId.epics.$epicId";
    page: "/admin/:journeyId/epics/:epicId";
  };
  "routes/admin.stories.tsx": {
    id: "routes/admin.stories";
    page: "/admin/:journeyId/stories";
  };
  "routes/admin.$journeyId.stories.$storyId.tsx": {
    id: "routes/admin.$journeyId.stories.$storyId";
    page: "/admin/:journeyId/stories/:storyId";
  };
  "routes/admin.$journeyId.tags.tsx": {
    id: "routes/admin.$journeyId.tags";
    page: "/admin/:journeyId/tags";
  };
  "routes/documentation.tsx": {
    id: "routes/documentation";
    page: "/documentation";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/api.tags": typeof import("./app/routes/api.tags.ts");
  "routes/api.tags.search": typeof import("./app/routes/api.tags.search.ts");
  "routes/api.tags.$tagId": typeof import("./app/routes/api.tags.$tagId.ts");
  "routes/journey": typeof import("./app/routes/journey.tsx");
  "routes/journey._index": typeof import("./app/routes/journey._index.tsx");
  "routes/journey.$id": typeof import("./app/routes/journey.$id.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin._index": typeof import("./app/routes/admin._index.tsx");
  "routes/admin.journeys": typeof import("./app/routes/admin.journeys.tsx");
  "routes/admin.$journeyId": typeof import("./app/routes/admin.$journeyId.tsx");
  "routes/admin.$journeyId._index": typeof import("./app/routes/admin.$journeyId._index.tsx");
  "routes/admin.altitude-info": typeof import("./app/routes/admin.altitude-info.tsx");
  "routes/admin.$journeyId.altitude-info.$altitudeInfoId": typeof import("./app/routes/admin.$journeyId.altitude-info.$altitudeInfoId.tsx");
  "routes/admin.epics": typeof import("./app/routes/admin.epics.tsx");
  "routes/admin.$journeyId.epics.$epicId": typeof import("./app/routes/admin.$journeyId.epics.$epicId.tsx");
  "routes/admin.stories": typeof import("./app/routes/admin.stories.tsx");
  "routes/admin.$journeyId.stories.$storyId": typeof import("./app/routes/admin.$journeyId.stories.$storyId.tsx");
  "routes/admin.$journeyId.tags": typeof import("./app/routes/admin.$journeyId.tags.tsx");
  "routes/documentation": typeof import("./app/routes/documentation.tsx");
};